name = "ExponentialRamsey"
defaultTargets = ["ExponentialRamsey"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"

[[lean_lib]]
name = "ExponentialRamsey"
